import { Inter } from "next/font/google";
import "./globals.css";
import { auth } from "@/auth";
import NextTopLoader from 'nextjs-toploader';
import Navbar from "@/components/ui/navbar";
const inter = Inter({ subsets: ["latin"] });
import { SessionProvider } from "next-auth/react";
import { Toaster } from "react-hot-toast";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await auth()
  return (
    <SessionProvider session={session}>
      <html lang="en">
        <body className={inter.className} suppressHydrationWarning={true} >
          <diV className="container min-h-screen items-center justify-between">
            <Navbar />
            <NextTopLoader position="top-right" />
            <Toaster />
            {children}
          </diV>
        </body>
      </html>
    </SessionProvider>
  );
}
