import Sidebar from "@/components/ui/sidebar";
import { Inter } from "next/font/google";
import "../globals.css";
const inter = Inter({ subsets: ["latin"] });
import { SessionProvider } from "next-auth/react";
import Providers from "@/components/providers";
import NextTopLoader from 'nextjs-toploader';
import { Toaster } from 'sonner';



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <NextTopLoader color="#2299DD" showSpinner={false} />
        <Toaster position="bottom-right" />
        <SessionProvider>
          {/* <AdminNavbar /> */}
          <Providers>
            <div className="flex mt-6">
              <Sidebar />
              {children}
            </div>
          </Providers>
        </SessionProvider>
      </body>
    </html>
  );
}
