import Sidebar from "@/components/ui/sidebar";
import "../globals.css";
export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function DashboardLayout({ children }) {

    return (

        <html lang="en">
            <body suppressHydrationWarning={true} >
                <div className="flex ">
                    <Sidebar />
                    {children}
                </div>
            </body>
        </html>

    );
}
