import { Inter } from "next/font/google";
import "../globals.css";
import Navbar from "@/components/ui/navbar";
import { SessionProvider } from "next-auth/react";
import Providers from "@/components/providers";
import Script from 'next/script'
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={inter.className}>
        <SessionProvider>
          <Providers>
            <div className="container">
              <Navbar />
              {children}
            </div>
            {process.env.NODE_ENV === 'production' &&
              <Script id="clarity-script" strategy="afterInteractive">
                {`
            (function(c,l,a,r,i,t,y){
                c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};
                t=l.createElement(r);t.async=1;t.src="https://www.clarity.ms/tag/"+i;
                y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);
            })(window, document, "clarity", "script", "${process.env.NEXT_PUBLIC_CLARITY_PROJECT_ID}");
          `}
              </Script>}

          </Providers>
        </SessionProvider>
      </body>
    </html>
  );
}
