import { Inter } from "next/font/google";
import "../globals.css";
import { auth } from "@/auth";
import Navbar from "@/components/ui/navbar";
const inter = Inter({ subsets: ["latin"] });
import { SessionProvider } from "next-auth/react";
import Providers from "@/components/providers";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await auth()
  return (
    <SessionProvider session={session}>
      <html lang="en">
        <body className={inter.className} suppressHydrationWarning={true} >
          <div className="container min-h-screen items-center justify-between">

            <Providers>
              <Navbar />
              {children}
            </Providers>
          </div>
        </body>
      </html>
    </SessionProvider>
  );
}
